### ISSUE TITLE
Peer to Peer Code Review

### ISSUE THREAD

**Issue by annaeliana7** [bernabasy/Portfolio#16]
### @bernabasy, Great job on your project so far! 🏆 

I have some suggestions to help polish your portfolio: 

- Ensure proper spelling on projects. Portfolio is misspelled, please correct it. As a suggestion, you may use grammarly or other English editing tools to help ensure your projects have correct spelling:
<img width="1073" alt="1  Portfolio-Name" src="https://user-images.githubusercontent.com/112557951/210316172-ff84c4ff-456f-4f9c-ad0e-7c11cf547e9a.png">

- Personalize your README file, you may add your personal logo, also please ensure that you fill in all the fields in the README file, and that you use the latest README Microverse version:
<img width="915" alt="2  README info" src="https://user-images.githubusercontent.com/112557951/210316881-093ecdd5-525a-4d7f-a958-07d6ca26a18f.png">

- For your personal Portfolio, you attached one of your completed projects, which looks great! However, you still have three projects to update/showcase. Please update: 
<img width="1569" alt="3  Items need to be filled" src="https://user-images.githubusercontent.com/112557951/210317239-28f3df1c-b19e-47fd-9313-053c98ec73f3.png">

Overall, your project looks really great!! Well done!! 🐶 🐾 🐾 🐾

**Comment by bernabasy** [comment]
Thanks change done
